#!/bin/sh

TASK="$1"

FORCED=false
args=`getopt f $*`
set -- $args
for i
do
	if [ "$i" = "-f" ]; then
		FORCED=true
	fi
done


function help () {
	echo "fwb - A script to help manage some of the fwb-specific SproutCore tasks";
	echo "";
	echo "tasks:";
	echo "	fwb build	- build the fwb project";
	echo "	fwb build-rails	- build the fwb project into the rails project";
	echo "	fwb clear-cache	- clear the cached files in both projects";
	echo "";
	echo "options:";
	echo "	-f		- remove old build result before rebuilding";
}

function destroyTmpFiles () {
	echo "destroying './tmp'..."
	rm -rf ./tmp
}

function destroyStaticFiles () {
	echo "destroying '../fwb_backend/public/static'..."
	rm -rf ../fwb_backend/public/static
}

case $TASK in
	build)
		if [ $FORCED = true ]; then
			destroyTmpFiles
		fi

		echo "building fwb project..."
		sc-build cwb
	;;
	build-rails)
		if [ $FORCED = true ]; then
			destroyTmpFiles
			destroyStaticFiles
		fi

		echo "building fwb project into rails project..."
		sc-build cwb --buildroot ../fwb_backend/public
	;;
	clear-cache)
		destroyTmpFiles
		destroyStaticFiles
	;;
	*)
		help
	;;
esac
